image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  BUILDX_VERSION: v0.9.1
  BUILDX_ARCH: linux-amd64

services:
  - docker:dind

build:
  stage: build
  script:
    - wget -O /usr/bin/docker-buildx
      https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.${BUILDX_ARCH}
    - chmod +x /usr/bin/docker-buildx
    - docker-buildx create --use
    - docker-buildx version
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-buildx build
      --platform linux/arm/v7,linux/arm64/v8,linux/amd64
      -t ${CI_REGISTRY_IMAGE}:latest
      -f ./Dockerfile
      --push
      .
